spring:
  profiles:
    active: spring.profiles.active
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers : true
app:
  datasource:
    #jdbc-url: jdbc:postgresql://host.docker.internal:5432/demodb
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password: 12345
    poll-size: 30
    platform : postgresql
