--CREATE TABLE person (
--    id UUID NOT NULL PRIMARY KEY,
--    name VARCHAR(100)  NOT NULL
--);
--
----
--CREATE TABLE weather (
--weatherId INT,
--temperature INT,
--weatherMain VARCHAR,
--weatherIcon VARCHAR,
--weatherDescription VARCHAR,
--countryCode VARCHAR,
--name NAME,
--timestamp INT,
--sunrise INT,
--sunset INT
--);
--
--DELETE FROM public.flyway_schema_history WHERE installed_rank = 1